spring.config.activate.on-profile: dev
spring.jpa.show-sql: true

security.jwt.secret: ${JWT_SECRET:mtxg0ay4oQdoVo4yxQJy9Li76AODSUHTiCzd8+u+saulOE2Cc2BU2tOpVrrD81nQ}
security.cookie.secure: false
logging.level.org.springframework.security.web.csrf=TRACE